import json
import ai_manager
import data_manager
import io_manager
import logic_manager

def get_file_path(file_path):
    if file_path == "":
        file_path = io_manager.get_shelter_filename()
    return file_path

# Maintained by Ming Xuan (2604426)
def main() -> None:
    file_path = ""
    while True:
        choice = io_manager.display_menu()
        # new client intake
        if choice == 1:
            client = io_manager.collect_intake_input()
            # TODO: ask user what file to save to
            clients = data_manager.load_records('clients.json') # Example: loading existing records from a JSON file
            if clients[1] is not None:
                print(f"Error loading clients: {clients[1]}")
            clients[0].append(client) # Add the new client to the list of existing clients
            data_manager.save_records('clients.json', clients[0]) # Example: saving to a JSON file
        # view all shelters
        elif choice == 2:
            shelters = data_manager.load_shelters(get_file_path(file_path))
            if shelters[1] is not None:
                print(f"Error loading shelters: {shelters[1]}")
            io_manager.print_shelter_list(shelters[0])
        # update csv file used
        elif choice == 3:
            # Direct update instead of using cache function
            file_path = io_manager.get_shelter_filename()
        # TODO: ask user what case file to use (could be generated by us in choice 1 or could be a csv already provided by the user)
        # TODO: then, pass the case(s) to AI manager for processing.
        # get shelter recommendations for clients
        elif choice == 4:
            file_path = get_file_path(file_path)
            # TODO: remove hardcoded file path and use the one provided by the user
            clients = data_manager.load_records('clients.json') # Example: loading existing records from a JSON file
            if clients[1] is not None:
                print(f"Error loading clients: {clients[1]}")
            shelters = data_manager.load_shelters(file_path)
            if shelters[1] is not None:
                print(f"Error loading shelters: {shelters[1]}")
            for client in clients[0]:
                print(f"\nGetting recommendations for client {client['client_id']}...")
                recommendation = ai_manager.get_shelter_recommendation(client, shelters[0])
                if recommendation is not None:
                    print(f"AI Recommendation for client {client['client_id']}:")
                    print(json.dumps(recommendation, indent=2))
                    print("Finding the best shelter based on AI recommendation and additional criteria...")
                    best_shelter = logic_manager.calculate_suitability_score(client, recommendation)
                    if best_shelter is not None:
                        print(f"Best shelter for client {client['client_id']}:")
                        print(json.dumps(best_shelter, indent=2))
                    else:
                        print(f"No suitable shelter found for client {client['client_id']} based on AI recommendation and additional criteria.")
                else:
                    print(f"No recommendations available for client {client['client_id']}.")
        # exit
        elif choice == 5:
            print("Thank you for using Social Service AI. Goodbye!")
            break
        # oob
        else:
            print("You have entered an invalid choice. Please try again.")

if __name__ == "__main__":
    main()